<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Monster', 'others');

/**
 * BaseMonster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $color1
 * @property integer $color2
 * @property integer $color3
 * @property integer $skin
 * @property string $nom
 * @property integer $exp
 * @property string $kamas
 * @property string $drop
 * @property integer $ai
 * @property Doctrine_Collection $Levels
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method integer             getColor1() Returns the current record's "color1" value
 * @method integer             getColor2() Returns the current record's "color2" value
 * @method integer             getColor3() Returns the current record's "color3" value
 * @method integer             getSkin()   Returns the current record's "skin" value
 * @method string              getNom()    Returns the current record's "nom" value
 * @method integer             getExp()    Returns the current record's "exp" value
 * @method string              getKamas()  Returns the current record's "kamas" value
 * @method string              getDrop()   Returns the current record's "drop" value
 * @method integer             getAi()     Returns the current record's "ai" value
 * @method Doctrine_Collection getLevels() Returns the current record's "Levels" collection
 * @method Monster             setId()     Sets the current record's "id" value
 * @method Monster             setColor1() Sets the current record's "color1" value
 * @method Monster             setColor2() Sets the current record's "color2" value
 * @method Monster             setColor3() Sets the current record's "color3" value
 * @method Monster             setSkin()   Sets the current record's "skin" value
 * @method Monster             setNom()    Sets the current record's "nom" value
 * @method Monster             setExp()    Sets the current record's "exp" value
 * @method Monster             setKamas()  Sets the current record's "kamas" value
 * @method Monster             setDrop()   Sets the current record's "drop" value
 * @method Monster             setAi()     Sets the current record's "ai" value
 * @method Monster             setLevels() Sets the current record's "Levels" collection
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMonster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('monster_templates');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('color1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('color2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('color3', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('skin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('exp', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kamas', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('drop', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ai', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MonsterLevel as Levels', array(
             'local' => 'id',
             'foreign' => 'templateid'));
    }
}