<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Zaapi', 'others');

/**
 * BaseZaapi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mapid
 * @property integer $cellid
 * @property integer $zone
 * @property Map $Map
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method integer getMapid()  Returns the current record's "mapid" value
 * @method integer getCellid() Returns the current record's "cellid" value
 * @method integer getZone()   Returns the current record's "zone" value
 * @method Map     getMap()    Returns the current record's "Map" value
 * @method Zaapi   setId()     Sets the current record's "id" value
 * @method Zaapi   setMapid()  Sets the current record's "mapid" value
 * @method Zaapi   setCellid() Sets the current record's "cellid" value
 * @method Zaapi   setZone()   Sets the current record's "zone" value
 * @method Zaapi   setMap()    Sets the current record's "Map" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZaapi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zaapis');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('mapid', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('cellid', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('zone', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map', array(
             'local' => 'mapid',
             'foreign' => 'id'));
    }
}