<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rule', 'accounts');

/**
 * BaseRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $content
 * 
 * @method text getContent() Returns the current record's "content" value
 * @method Rule setContent() Sets the current record's "content" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rule');
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}