<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GiftTemplate', 'others');

/**
 * BaseGiftTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property text $description
 * @property varchar $img_url
 * @property varchar $items
 * @property int $price
 * @property bool $max
 * @property Item $Item
 * @property Doctrine_Collection $GiftAccount
 * 
 * @method varchar             getName()        Returns the current record's "name" value
 * @method text                getDescription() Returns the current record's "description" value
 * @method varchar             getImgUrl()      Returns the current record's "img_url" value
 * @method varchar             getItems()       Returns the current record's "items" value
 * @method int                 getPrice()       Returns the current record's "price" value
 * @method bool                getMax()         Returns the current record's "max" value
 * @method Item                getItem()        Returns the current record's "Item" value
 * @method Doctrine_Collection getGiftAccount() Returns the current record's "GiftAccount" collection
 * @method GiftTemplate        setName()        Sets the current record's "name" value
 * @method GiftTemplate        setDescription() Sets the current record's "description" value
 * @method GiftTemplate        setImgUrl()      Sets the current record's "img_url" value
 * @method GiftTemplate        setItems()       Sets the current record's "items" value
 * @method GiftTemplate        setPrice()       Sets the current record's "price" value
 * @method GiftTemplate        setMax()         Sets the current record's "max" value
 * @method GiftTemplate        setItem()        Sets the current record's "Item" value
 * @method GiftTemplate        setGiftAccount() Sets the current record's "GiftAccount" collection
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGiftTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gift_templates');
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('img_url', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('items', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('price', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('max', 'bool', null, array(
             'type' => 'bool',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Item', array(
             'local' => 'items',
             'foreign' => 'id'));

        $this->hasMany('GiftAccount', array(
             'local' => 'id',
             'foreign' => 'gift_id'));
    }
}