<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NpcResponse', 'others');

/**
 * BaseNpcResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $responseid
 * @property integer $type
 * @property string $args
 * 
 * @method integer     getResponseid() Returns the current record's "responseid" value
 * @method integer     getType()       Returns the current record's "type" value
 * @method string      getArgs()       Returns the current record's "args" value
 * @method NpcResponse setResponseid() Sets the current record's "responseid" value
 * @method NpcResponse setType()       Sets the current record's "type" value
 * @method NpcResponse setArgs()       Sets the current record's "args" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNpcResponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('npc_response');
        $this->hasColumn('responseid', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('args', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}