<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MapTrigger', 'others');

/**
 * BaseMapTrigger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mapid
 * @property integer $cellid
 * @property string $newmap
 * @property Map $StartMap
 * 
 * @method integer    getId()       Returns the current record's "id" value
 * @method integer    getMapid()    Returns the current record's "mapid" value
 * @method integer    getCellid()   Returns the current record's "cellid" value
 * @method string     getNewmap()   Returns the current record's "newmap" value
 * @method Map        getStartMap() Returns the current record's "StartMap" value
 * @method MapTrigger setId()       Sets the current record's "id" value
 * @method MapTrigger setMapid()    Sets the current record's "mapid" value
 * @method MapTrigger setCellid()   Sets the current record's "cellid" value
 * @method MapTrigger setNewmap()   Sets the current record's "newmap" value
 * @method MapTrigger setStartMap() Sets the current record's "StartMap" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapTrigger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maps_triggers');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('mapid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cellid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('newmap', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map as StartMap', array(
             'local' => 'mapid',
             'foreign' => 'id'));
    }
}