<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FAQ', 'accounts');

/**
 * BaseFAQ
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $question
 * @property text $answer
 * 
 * @method text getQuestion() Returns the current record's "question" value
 * @method text getAnswer()   Returns the current record's "answer" value
 * @method FAQ  setQuestion() Sets the current record's "question" value
 * @method FAQ  setAnswer()   Sets the current record's "answer" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFAQ extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('f_a_q');
        $this->hasColumn('question', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('answer', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}