<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Config', 'accounts');

/**
 * BaseConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $key
 * @property text $value
 * 
 * @method varchar getKey()   Returns the current record's "key" value
 * @method text    getValue() Returns the current record's "value" value
 * @method Config  setKey()   Sets the current record's "key" value
 * @method Config  setValue() Sets the current record's "value" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config');
        $this->hasColumn('key', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}