<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Exp', 'others');

/**
 * BaseExp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $level
 * @property integer $character
 * @property integer $job
 * @property integer $mount
 * @property integer $pvp
 * 
 * @method integer getLevel()     Returns the current record's "level" value
 * @method integer getCharacter() Returns the current record's "character" value
 * @method integer getJob()       Returns the current record's "job" value
 * @method integer getMount()     Returns the current record's "mount" value
 * @method integer getPvp()       Returns the current record's "pvp" value
 * @method Exp     setLevel()     Sets the current record's "level" value
 * @method Exp     setCharacter() Sets the current record's "character" value
 * @method Exp     setJob()       Sets the current record's "job" value
 * @method Exp     setMount()     Sets the current record's "mount" value
 * @method Exp     setPvp()       Sets the current record's "pvp" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exp_data');
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('character', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('job', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('mount', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pvp', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}