<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MapObject', 'others');

/**
 * BaseMapObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $walkable
 * @property string $objectlist
 * @property string $actionlist
 * @property integer $respawn
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getName()       Returns the current record's "name" value
 * @method integer   getWalkable()   Returns the current record's "walkable" value
 * @method string    getObjectlist() Returns the current record's "objectlist" value
 * @method string    getActionlist() Returns the current record's "actionlist" value
 * @method integer   getRespawn()    Returns the current record's "respawn" value
 * @method MapObject setId()         Sets the current record's "id" value
 * @method MapObject setName()       Sets the current record's "name" value
 * @method MapObject setWalkable()   Sets the current record's "walkable" value
 * @method MapObject setObjectlist() Sets the current record's "objectlist" value
 * @method MapObject setActionlist() Sets the current record's "actionlist" value
 * @method MapObject setRespawn()    Sets the current record's "respawn" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maps_objects');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('walkable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('objectlist', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('actionlist', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('respawn', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}