<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SpellLearn', 'others');

/**
 * BaseSpellLearn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $classe
 * @property integer $level
 * @property integer $spellid
 * @property integer $position
 * @property Spell $Spell
 * 
 * @method integer    getId()       Returns the current record's "id" value
 * @method integer    getClasse()   Returns the current record's "classe" value
 * @method integer    getLevel()    Returns the current record's "level" value
 * @method integer    getSpellid()  Returns the current record's "spellid" value
 * @method integer    getPosition() Returns the current record's "position" value
 * @method Spell      getSpell()    Returns the current record's "Spell" value
 * @method SpellLearn setId()       Sets the current record's "id" value
 * @method SpellLearn setClasse()   Sets the current record's "classe" value
 * @method SpellLearn setLevel()    Sets the current record's "level" value
 * @method SpellLearn setSpellid()  Sets the current record's "spellid" value
 * @method SpellLearn setPosition() Sets the current record's "position" value
 * @method SpellLearn setSpell()    Sets the current record's "Spell" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpellLearn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spells_learn');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('classe', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('spellid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Spell', array(
             'local' => 'spellid',
             'foreign' => 'id'));
    }
}