<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NpcMap', 'others');

/**
 * BaseNpcMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mapid
 * @property integer $templateid
 * @property integer $cell
 * @property integer $dir
 * @property Map $Map
 * @property Npc $Npc
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getMapid()      Returns the current record's "mapid" value
 * @method integer getTemplateid() Returns the current record's "templateid" value
 * @method integer getCell()       Returns the current record's "cell" value
 * @method integer getDir()        Returns the current record's "dir" value
 * @method Map     getMap()        Returns the current record's "Map" value
 * @method Npc     getNpc()        Returns the current record's "Npc" value
 * @method NpcMap  setId()         Sets the current record's "id" value
 * @method NpcMap  setMapid()      Sets the current record's "mapid" value
 * @method NpcMap  setTemplateid() Sets the current record's "templateid" value
 * @method NpcMap  setCell()       Sets the current record's "cell" value
 * @method NpcMap  setDir()        Sets the current record's "dir" value
 * @method NpcMap  setMap()        Sets the current record's "Map" value
 * @method NpcMap  setNpc()        Sets the current record's "Npc" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNpcMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('npcs_maps');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('mapid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('templateid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cell', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map', array(
             'local' => 'mapid',
             'foreign' => 'id'));

        $this->hasOne('Npc', array(
             'local' => 'templateid',
             'foreign' => 'id'));
    }
}