<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollOption', 'accounts');

/**
 * BasePollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $poll_id
 * @property string $name
 * @property Doctrine_Collection $Polleds
 * @property Poll $Poll
 * 
 * @method integer             getPollId()  Returns the current record's "poll_id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getPolleds() Returns the current record's "Polleds" collection
 * @method Poll                getPoll()    Returns the current record's "Poll" value
 * @method PollOption          setPollId()  Sets the current record's "poll_id" value
 * @method PollOption          setName()    Sets the current record's "name" value
 * @method PollOption          setPolleds() Sets the current record's "Polleds" collection
 * @method PollOption          setPoll()    Sets the current record's "Poll" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_option');
        $this->hasColumn('poll_id', 'integer', 9, array(
             'type' => 'integer',
             'length' => 9,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PollAccount as Polleds', array(
             'local' => 'id',
             'foreign' => 'poll_option_id'));

        $this->hasOne('Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id'));
    }
}