<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rank', 'accounts');

/**
 * BaseRank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property string $name
 * @property Account $Account
 * 
 * @method integer getAccountId()  Returns the current record's "account_id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method Account getAccount()    Returns the current record's "Account" value
 * @method Rank    setAccountId()  Sets the current record's "account_id" value
 * @method Rank    setName()       Sets the current record's "name" value
 * @method Rank    setAccount()    Sets the current record's "Account" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rank');
        $this->hasColumn('account_id', 'integer', 9, array(
             'type' => 'integer',
             'length' => 9,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));
    }
}