<?php

/**
 * BaseTicketAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id
 * @property int $ticket_id
 * @property int $author_id
 * @property text $content
 * @property Ticket $Ticket
 * @property Account $Author
 * 
 * @method int          getId()        Returns the current record's "id" value
 * @method int          getTicketId()  Returns the current record's "ticket_id" value
 * @method int          getAuthorId()  Returns the current record's "author_id" value
 * @method text         getContent()   Returns the current record's "content" value
 * @method Ticket       getTicket()    Returns the current record's "Ticket" value
 * @method Account      getAuthor()    Returns the current record's "Author" value
 * @method TicketAnswer setId()        Sets the current record's "id" value
 * @method TicketAnswer setTicketId()  Sets the current record's "ticket_id" value
 * @method TicketAnswer setAuthorId()  Sets the current record's "author_id" value
 * @method TicketAnswer setContent()   Sets the current record's "content" value
 * @method TicketAnswer setTicket()    Sets the current record's "Ticket" value
 * @method TicketAnswer setAuthor()    Sets the current record's "Author" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicketAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket_answer');
        $this->hasColumn('id', 'int', 9, array(
             'type' => 'int',
             'length' => 9,
             ));
        $this->hasColumn('ticket_id', 'int', 9, array(
             'type' => 'int',
             'length' => 9,
             ));
        $this->hasColumn('author_id', 'int', 9, array(
             'type' => 'int',
             'length' => 9,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id'));

        $this->hasOne('Account as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}