<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Spell', 'others');

/**
 * BaseSpell
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property integer $sprite
 * @property string $spriteinfos
 * @property string $lvl1
 * @property string $lvl2
 * @property string $lvl3
 * @property string $lvl4
 * @property string $lvl5
 * @property string $lvl6
 * @property SpellLearn $SpellLearn
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getNom()         Returns the current record's "nom" value
 * @method integer    getSprite()      Returns the current record's "sprite" value
 * @method string     getSpriteinfos() Returns the current record's "spriteinfos" value
 * @method string     getLvl1()        Returns the current record's "lvl1" value
 * @method string     getLvl2()        Returns the current record's "lvl2" value
 * @method string     getLvl3()        Returns the current record's "lvl3" value
 * @method string     getLvl4()        Returns the current record's "lvl4" value
 * @method string     getLvl5()        Returns the current record's "lvl5" value
 * @method string     getLvl6()        Returns the current record's "lvl6" value
 * @method SpellLearn getSpellLearn()  Returns the current record's "SpellLearn" value
 * @method Spell      setId()          Sets the current record's "id" value
 * @method Spell      setNom()         Sets the current record's "nom" value
 * @method Spell      setSprite()      Sets the current record's "sprite" value
 * @method Spell      setSpriteinfos() Sets the current record's "spriteinfos" value
 * @method Spell      setLvl1()        Sets the current record's "lvl1" value
 * @method Spell      setLvl2()        Sets the current record's "lvl2" value
 * @method Spell      setLvl3()        Sets the current record's "lvl3" value
 * @method Spell      setLvl4()        Sets the current record's "lvl4" value
 * @method Spell      setLvl5()        Sets the current record's "lvl5" value
 * @method Spell      setLvl6()        Sets the current record's "lvl6" value
 * @method Spell      setSpellLearn()  Sets the current record's "SpellLearn" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpell extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spells_data');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('sprite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('spriteinfos', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0,0,0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('lvl1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lvl2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lvl3', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lvl4', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lvl5', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lvl6', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpellLearn', array(
             'local' => 'id',
             'foreign' => 'spellid'));
    }
}