<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MonsterLevel', 'others');

/**
 * BaseMonsterLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $templateid
 * @property integer $level
 * @property integer $pa
 * @property integer $pm
 * @property integer $vie
 * @property integer $size
 * @property string $caracts
 * @property string $resistances
 * @property string $spells
 * @property Monster $Monster
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getTemplateid()  Returns the current record's "templateid" value
 * @method integer      getLevel()       Returns the current record's "level" value
 * @method integer      getPa()          Returns the current record's "pa" value
 * @method integer      getPm()          Returns the current record's "pm" value
 * @method integer      getVie()         Returns the current record's "vie" value
 * @method integer      getSize()        Returns the current record's "size" value
 * @method string       getCaracts()     Returns the current record's "caracts" value
 * @method string       getResistances() Returns the current record's "resistances" value
 * @method string       getSpells()      Returns the current record's "spells" value
 * @method Monster      getMonster()     Returns the current record's "Monster" value
 * @method MonsterLevel setId()          Sets the current record's "id" value
 * @method MonsterLevel setTemplateid()  Sets the current record's "templateid" value
 * @method MonsterLevel setLevel()       Sets the current record's "level" value
 * @method MonsterLevel setPa()          Sets the current record's "pa" value
 * @method MonsterLevel setPm()          Sets the current record's "pm" value
 * @method MonsterLevel setVie()         Sets the current record's "vie" value
 * @method MonsterLevel setSize()        Sets the current record's "size" value
 * @method MonsterLevel setCaracts()     Sets the current record's "caracts" value
 * @method MonsterLevel setResistances() Sets the current record's "resistances" value
 * @method MonsterLevel setSpells()      Sets the current record's "spells" value
 * @method MonsterLevel setMonster()     Sets the current record's "Monster" value
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMonsterLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('monster_levels');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('templateid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pm', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vie', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('size', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caracts', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('resistances', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('spells', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Monster', array(
             'local' => 'templateid',
             'foreign' => 'id'));
    }
}