<?php

/**
 * AccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Account');
    }

	public function ban($ids)
	{
		return $this->executeBanQuery(true, $ids);
	}
	public function unBan($ids)
	{
		return $this->executeBanQuery(false, $ids);
	}
	public function executeBanQuery($ban, $ids = null,  $q = null)
	{
		if (null === $q)
		{
			$q = Doctrine_Query::create();
		}

		$q
			->update('Account')
				->set('banned', $ban);
		if (null !== $ids)
		{
			$q->whereIn('id', $ids);
		}

		return $q->execute();
	}
}