<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	public function updateAuthor()
	{
		$this->setAuthor(sfContext::getInstance()->getUser()->getAccount());
	}

	public function getCommentsCount()
	{
		if (sfContext::getInstance()->getUser()->hasCredential('comment.manage'))
			return $this->Comments->count();

		$count = 0;
		foreach ($this->Comments as $comment)
		{
			if (!$comment->getDeletedAt())
			{
				$count++;
			}
		}

		return $count;
	}
}
