<?php

/**
 * ConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Config');
    }
}