<?php

/**
 * Contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contact extends BaseContact
{
	public function preInsert($event)
	{ //we must *NOT* update infos when updated !
		$this->Author = sfContext::getInstance()->getUser()->getAccount();
	}
}