<?php

/**
 * DungeonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DungeonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DungeonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dungeon');
    }
}