<?php

/**
 * FAQTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FAQTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FAQTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FAQ');
    }
}