<?php

/**
 * GiftAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GiftAccount');
    }
}