<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Item extends BaseItem
{
	public function getName()
	{ //the override is needed because of double-utf8 encoding
		return utf8_decode(utf8_encode($this->_get('name')));
	}
	public function hasStats()
	{
		return !empty($this->stats);
	}
	public function parseStats($isMax = false)
	{
		if (!$this->hasStats())
		{
			return '';
		}

		return sfContext::getInstance()->get('IG_inflector')->parseStats($this->stats, $isMax);
	}
}
