<?php

/**
 * MapObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapObject');
    }
}