<?php

/**
 * MapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Map');
    }
}