<?php

/**
 * MapTriggerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapTriggerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapTriggerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapTrigger');
    }
}