<?php

/**
 * MonsterLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MonsterLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MonsterLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MonsterLevel');
    }
}