<?php

/**
 * MonsterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MonsterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MonsterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Monster');
    }
}