<?php

/**
 * NpcQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NpcQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NpcQuestion');
    }
}