<?php

/**
 * NpcResponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcResponseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NpcResponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NpcResponse');
    }
}