<?php

/**
 * PanoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PanoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PanoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pano');
    }
}