<?php

/**
 * PollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PollOption extends BasePollOption
{
	public function getPercent()
	{
		return 0 === $this->Poll->getPolledsCount() ? 0 : round(100*($this->Polleds->count() / $this->Poll->getPolledsCount()), 2);
	}
}
