<?php

/**
 * PollAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollAccount');
    }
}