<?php

/**
 * PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Poll');
    }
}