<?php

/**
 * Poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DGuardCMS
 * @subpackage model
 * @author     Andaeriel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Poll extends BasePoll
{
	protected $polledsCount = -1;

	public function getPolledsCount($refresh = false)
	{
		if (-1 === $this->polledsCount || $refresh)
		{
			$this->polledsCount = 0;
			foreach ($this->getOptions() as $option)
			{
				$this->polledsCount += $option->getPolleds()->count();
			}
		}

		return $this->polledsCount;
	}
}
