<?php

/**
 * RankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rank');
    }
}