<?php

/**
 * RuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rule');
    }
}