<?php

/**
 * TicketCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketCategory');
    }
}