<?php

/**
 * TicketAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketAnswer');
    }
}