<?php

/**
 * ZaapiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZaapiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZaapiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zaapi');
    }
}