<?php

/**
 * ZaapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZaapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZaapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zaap');
    }
}