generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Zaapi
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          zaapi
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        mapid: { label: Map }
        cellid: { label: Cell ID }
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
